name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: "114.0.5735.90"  # Stable ve test edilmiş bir versiyon
        
    - name: Run Tests
      run: |
        # Install and setup Xvfb
        sudo apt-get update
        sudo apt-get install -y xvfb
        
        # Start Xvfb
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3
        export DISPLAY=:99
        
        # Run tests without headless mode
        mvn clean test -Dheadless=false
    
    - name: Store Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results
        retention-days: 30