name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Run Tests
      run: |
        # Xvfb'yi başlat
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3  # Xvfb'nin başlaması için bekle
        
        # Chrome'u yapılandır ve testleri çalıştır
        mvn clean test \
          -Dbrowser=chrome \
          -Dheadless=true \
          -Dwebdriver.chrome.whitelistedIps="" \
          -Dselenium.window-size=1920,1080 \
          -Dwebdriver.chrome.arguments="--no-sandbox,--disable-dev-shm-usage"
        
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Generate Allure Report
      run: |
        mvn allure:report
        mvn allure:aggregate
      
    - name: Store Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: |
          target/site/allure-maven-plugin/
          target/allure-results/
        retention-days: 30
        